BUTTON_CONFIRM_YES = "//button[text()='Да']"
BUTTON_NEXT = "//button[text()='Далее']"
BUTTON_ORDER = "//div[contains(@class, 'Order_Buttons')]//button[text()='Заказать']"
CHECKBOX_BLACK = "//input[@id='black']"
CHECKBOX_GREY = "//input[@id='grey']"
DROPDOWN_RENTAL_PERIOD = "//div[contains(@class, 'Dropdown-root')]"
FIELD_ADDRESS = "//input[@placeholder='* Адрес: куда привезти заказ']"
FIELD_COMMENT = "//input[@placeholder='Комментарий для курьера']"
FIELD_DATE = "//input[@placeholder='* Когда привезти самокат']"
FIELD_NAME = "//input[@placeholder='* Имя']"
FIELD_PHONE = "//input[@placeholder='* Телефон: на него позвонит курьер']"
FIELD_SURNAME = "//input[@placeholder='* Фамилия']"
METRO_STATION_INPUT = "//input[@placeholder='* Станция метро']"
METRO_STATION_OPTION = "//button[contains(@class, 'Order_SelectOption') and .//div[text()='{}']]"
MODAL_CONFIRM = "//div[contains(@class, 'Order_Modal')]"
MODAL_SUCCESS_TEXT = "//div[contains(@class, 'Order_Modal')]//div[text()='Заказ оформлен']"
MODAL_SUCCESS_ORDER = "//button[text()='Посмотреть статус']"
RENTAL_PERIOD_OPTION = "//div[contains(@class, 'Dropdown-option') and text()='{}']"
